### ISSUE TITLE
Erro na exportação do alertas em periódicos de publicação contínua

### ISSUE THREAD

**Issue by carolinatanigushi** [scieloorg/scielo_exports#2]
Em alguns casos o alerta não é exportado por completo ([alerta.txt](https://github.com/scieloorg/scielo_exports/files/4214325/alerta.txt)). Fiz alguns testes e parece ser algum problema específico com periódicos de publicação contínua. Gravei dois vídeos de teste, um com a TCE (publicação contínua) e outro com a JBN (publicação regular).
- [Erro na exportação do alerta da TCE](https://youtu.be/YC1KAVpTR6Y)
- [Teste de exportação de alerta da JBN](https://youtu.be/7Zy4ky8RFfo)

**Comment by ednilson** [comment]
Foi criado um arquivo .BAT para preparo de variáveis de ambiente (encoding) e execução do executável.
O script deverá ser executado sempre através do .BAT.

**Comment by ednilson** [comment]
Foi criado um arquivo .BAT para preparo de variáveis de ambiente (encoding) e execução do executável.
O script deverá ser executado sempre através do .BAT.
