### ISSUE TITLE
Erro na exportação do alertas

### ISSUE THREAD

**Issue by carolinatanigushi** [scieloorg/scielo_exports#3]
Ao tentar executar o arquivo issue_alerts.bat, estou recebendo o erro a seguir:

![image](https://user-images.githubusercontent.com/12699183/92476323-262bca00-f1b5-11ea-8273-ffd8d0d665fc.png)

O PID do fascículo que estou tentando gerar é **0104-070720200001**

Obrigada!

**Comment by ednilson** [comment]
Faltava a pasta como template do jinja2. 
Foi adicionado na última versão compilada.
