### ISSUE TITLE
Possibilidade de gerar alertas com uma lista de PIDs dos artigos

### ISSUE THREAD

**Issue by carolinatanigushi** [scieloorg/scielo_exports#4]
Alertas de periódicos em publicação contínua em volume único são enviados periodicamente (por exemplo, uma vez por mês, uma vez a cada três meses, etc). Nesses casos, a equipe da Francine envia uma lista com os artigos que devem constar nesse alerta.

Atualmente, estou gerando um HTML com todos os artigos do fascículo e removendo os artigos que não devem estar lá. O ideal seria listar os artigos pelo PID e gerar automaticamente um HTML do alerta com apenas esses artigos.

Obrigada!

**Comment by ednilson** [comment]
@carolinatanigushi Está disponível a versão 2.0. Baixe por este link [aqui](https://github.com/scieloorg/scielo_exports/raw/master/issue_alerts/dist/issue_alerts.zip).
Para produzir o HTML para um artigo eu adotei a URL do artigo no novo site. 
Ex.:
`https://www.scielo.br/j/bn/a/jCJccdm5KJdKxvCVBbcGtMv/?lang=en`
Assim você não precisa do PID antigo.
Veja se tudo bem assim.

**Comment by carolinatanigushi** [comment]
Fiz os testes e esta questão parece estar resolvida. No entanto, o programa gera um arquivo para cada artigo, o ideal seria que ele gerasse um único arquivo com todos os artigos listados na issue_list.txt.

**Comment by carolinatanigushi** [comment]
Fechando este ticket pois foi resolvido.
