### ISSUE TITLE
Itálicos dos títulos dos artigos não são mantidos na conversão

### ISSUE THREAD

**Issue by carolinatanigushi** [scieloorg/scielo_exports#6]
Os itálicos dos títulos dos artigos não são mantidos na conversão, por exemplo o sumário do [v20n3 da BN](https://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1676-060320200003&lng=en&nrm=iso). Os artigos **Description of mating behavior, life cycle, and antennal sensilla of _Cyclocephala putrida_ Burmeister, 1847 (Coleoptera, Scarabaeidae, Dynastinae)** e **Sympatry between species of _Juliomys_ (Rodentia: Sigmodontinae) along an altitudinal gradient in the Serra da Bocaina National Park**.

O HTML está disponível em: https://gist.github.com/carolinatanigushi/01beb687e5e083f0079a2ae834fad5a9

**Comment by ednilson** [comment]
Código para obtençao do html do titulo:

**Comment by robertatakenaka** [comment]
@ednilson @carolinatanigushi @gustavofonseca 
Os registro h contém dados sem nenhuma formatação de html pois são usados na indexação. Os registros do tipo f contém os mesmos dados com a formatação html. Acontece que o AM, foi carregado usando os dados do registro h, que tb usamos para montar o sumário no site novo. Os dados ficarão corretos quando o fluxo de publicação não depender mais das bases isis. Se olhar o título na página do artigo pode ter os itálicos. Detalhe: abrir alguns documentos em que o original, até mesmo no PDF estava sem o itálico.

**Comment by ednilson** [comment]
@robertatakenaka obrigado pelas informações.
Eu já havia verificado isso.  O comentário da obtenção do html é um lembrete para mim para tentar aplicar neste script.

**Comment by ednilson** [comment]
@carolinatanigushi acompanhe:

Para remover a tag `<p class="title"></p>` e manter seu conteúdo.
Exemplo:
```
soup = BeautifulSoup('<p><strong><p class="title">Seed removal of <em>Araucaria angustifolia</em> by native and invasive mammals in protected areas of Atlantic Forest</p></strong></p>', 'html')
soup.find_all('p', {'class':'title'})[0].replaceWithChildren()
```
Resultado:
`<p><strong>Seed removal of <em>Araucaria angustifolia</em> by native and invasive mammals in protected areas of Atlantic Forest</strong></p>`

**Comment by ednilson** [comment]
referências:
Fascículo: https://www.scielo.br/j/bn/i/2021.v21n1/
Artigo: https://www.scielo.br/j/bn/a/ZQR6dX35Pv47FMx9QTLty3R/?lang=en
PID do artigo não é mais visível: https://github.com/scieloorg/opac/issues/994
Formatação dos títulos: https://github.com/scieloorg/opac/issues/1484

**Comment by carolinatanigushi** [comment]
Resolvido na nova versão!

**Comment by carolinatanigushi** [comment]
Fechando este ticket pois foi resolvido.
